snap: refresh for `base: core22`

diff --git a/wrapper/wrapper b/wrapper/wrapper
--- a/wrapper/wrapper
+++ b/wrapper/wrapper
@@ -1,9 +1,9 @@
 #!/bin/bash
 set -e
 
-if ! snapctl is-connected graphics-core20; then
-  echo "ERROR: You need to connect the graphics-core20 interface."
-  echo "e.g. sudo snap connect $SNAP_INSTANCE_NAME:graphics-core20 mesa-core20:graphics-core20"
+if ! snapctl is-connected graphics-core22; then
+  echo "ERROR: You need to connect the graphics-core22 interface."
+  echo "e.g. sudo snap connect $SNAP_INSTANCE_NAME:graphics-core22 mesa-core22:graphics-core22"
   exit 1
 fi
 
